micronaut:
  application:
    name: favorites-app
  server:
    host: ${favorites-app-host:localhost}
    port: 8081
    idle-timeout: 2000ms
  http:
    client.connect-ttl: 30m
    client.pool.acquire-timeout: 2000ms
    services:
      carts-api:
        urls:
          - "https://stgapi-internal.target.com"
        connect-timeout: 300ms
        read-timeout: 1000ms
        pool:
          enabled: true
          max-connections: 128
          max-pending-acquires: 50

  metrics:
    binders:
      web:
        enabled: false # we are using our own binder via our custom micronaut-metrics lib

lists:
  metrics:
    binders:
      http:
        enabled: true # we are using our own binder via our custom micronaut-metrics lib

jackson:
  property-naming-strategy: "SNAKE_CASE"

filter:
  server:
    order:
      mdc-filter: 50
      lists-brave-tracing-server-filter: 100
      authorization-filter: 200
      sanitizing-filter: 300
  client:
    order:
      lists-brave-tracing-client-filter: 900
      resilience-client-filter: 800
      oauth-filter: 701
      oauth-key-filter: 700

logging:
  mdc:
    enabled: true
    keys:
      - profile_id
      - x-api-id
    filter:
      path: /lists/**

resilience4j:
  circuitbreaker:
    failure-rate-threshold: 50            # failure rate threshold in percentage (default: 50)
    wait-duration-secs-in-open-state: 10  # time cb waits before transitioning from open to half-open (default: 60s)
    sliding-window-type: TIME_BASED       # possible values TIME_BASED or COUNT_BASED (default: COUNT_BASED)
    sliding-window-size: 100               # seconds for TIME_BASED, request-count for COUNT_BASED (default: 100)
    minimum-number-of-calls: 10            # min calls required (per sliding window period) before cb calculates error rate (default: 10)

tracing:
  zipkin:
    enabled: false
    excluded-paths: /health
    b3-propagation-suppress: true
    sample-rate-percent: 0.5
    http:
      url: "https://zipkinserver.dev.target.com"
      messageMaxBytes: 50000
    app:
      name: shoppinglist
      env: stage
      region: tdc

cart:
  client:
    refresh-cycle-sec: 999999999

list:
  list-type: FAVORITES
  max-count: 50
  max-pending-item-count: 100
  max-completed-items-count: 100
  abandon-after-duration-in-days: 730 # It is two years duration
  get-favorites-max-tcin-count: 28
  default-list-title: "My Favorites"
  page-size: 28
  features.two-carts: false
  features.dedupe: false
  features.sort-position: false
  features.fixed-default-list: true

sic:
  batch-size: 50

msgbus:
  source: favorites
  kafka:
    consumer:
      enabled: false
    producer:
      enabled: true
    dlqconsumer:
      enabled: false
    dlqproducer:
      enabled: true
    topic: lists-msg-bus
    consumer-group: favorites-msg-bus-consumer
    consumer-batch-size: 10
    dlq-topic: lists-dlq
    dlq-consumer-group: favorites-dlq-consumer
    dlq-event-retry-interval-secs: 1
    dlq-max-event-retry-count: 2
    dlq-consumer-batch-size: 10

